var FamebookConstants = {
  POSTS_RECEIVED: "POSTS_RECEIVED",
  NEW_POST_RECEIVED: "NEW_POST_RECEIVED",
  DELETED_POST_RECEIVED: "DELETED_POST_RECEIVED",
  ALL_USERS_RECEIVED: "ALL_USERS_RECEIVED",
  USER_RECEIVED: "USER_RECEIVED",
  REQUESTEE_RECEIVED: "REQUESTEE_RECEIVED",
  FRIENDSHIPS_RECEIVED: "FRIENDSHIPS_RECEIVED"
};

module.exports = FamebookConstants;
